version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: barnes-rais-backend:latest
    container_name: barnes-rais-backend
    restart: always
    ports:
      - "${PORT:-3001}:3001"
    env_file:
      - .env
    depends_on:
      - db-migration

  db-migration:
    build:
      context: .
      dockerfile: Dockerfile
    image: barnes-rais-backend:latest
    command: bun run schema:push
    env_file:
      - .env
    restart: on-failure
