version: "3.8"

services:
  db-migration:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: barnes-rais-backend:latest
    command: bun run db:mg
    env_file:
      - .env
    restart: on-failure
    network_mode: "host"
