version: "3.8"

services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: barnes-rais-backend:latest
    container_name: barnes-rais-backend
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - .env
