version: "3.8"

services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: barnes-rais-backend:latest
    container_name: barnes-rais-backend
    restart: always
    ports:
      - "3443:3443"
    env_file:
      - .env
    environment:
      - IS_CONTAINER=true
    volumes:
      - ${HOME}/barnes_rais_training/training_data:/app/barnes_rais_training/training_data
